//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EpgTimerSrv.rc
//
#define IDC_MYICON                      2
#define IDD_EPGTIMERSRV_DIALOG          102
#define IDI_ICON_GRAY                   107
#define IDI_ICON_SEMI                   108
#define IDI_ICON_BLUE                   109
#define IDI_ICON_GREEN                  110
#define IDI_ICON_RED                    111
#define IDS_VERSION_TEXT                115
#define IDD_DIALOG_SETTING              120
#define IDD_DIALOG_SETTING_BASIC        121
#define IDD_DIALOG_SETTING_EPG          122
#define IDD_DIALOG_SETTING_REC          123
#define IDD_DIALOG_SETTING_RESERVE      124
#define IDD_DIALOG_SETTING_OTHER        125
#define IDR_MAINFRAME                   128
#define IDR_MENU_TRAY                   129
#define IDC_STATIC_SHUTDOWN             1000
#define IDC_PROGRESS_SHUTDOWN           1001
#define IDC_BUTTON_SETTING              32770
#define IDC_BUTTON_S3                   32771
#define IDC_BUTTON_S4                   32772
#define IDC_BUTTON_END                  32773
#define IDC_BUTTON_GUI                  32774
#define IDC_MENU_RESERVE                32775
#define IDC_MENU_RESERVE_MAX            32874
#define IDC_MENU_STREAMING              32875
#define IDC_MENU_STREAMING_MAX          32974
#define IDC_BUTTON_STREAMING_NWPLAY     32975
#define IDC_TAB                                 40000
#define IDC_BUTTON_OK                           40001
#define IDC_EDIT_SET_DATA_SAVE_PATH             40100
#define IDC_BUTTON_SET_DATA_SAVE_PATH           40101
#define IDC_EDIT_SET_REC_EXE_PATH               40102
#define IDC_BUTTON_SET_REC_EXE_PATH             40103
#define IDC_EDIT_SET_REC_CMD_BON                40104
#define IDC_EDIT_SET_REC_CMD_MIN                40105
#define IDC_EDIT_SET_REC_CMD_VIEW_OFF           40106
#define IDC_EDIT_SET_REC_CMD_ONID               40107
#define IDC_EDIT_SET_REC_CMD_TSID               40108
#define IDC_EDIT_SET_REC_CMD_SID                40109
#define IDC_LIST_SET_REC_FOLDER                 40110
#define IDC_EDIT_SET_REC_FOLDER                 40111
#define IDC_BUTTON_SET_REC_FOLDER               40112
#define IDC_BUTTON_SET_REC_FOLDER_UP            40113
#define IDC_BUTTON_SET_REC_FOLDER_DN            40114
#define IDC_BUTTON_SET_REC_FOLDER_ADD           40115
#define IDC_BUTTON_SET_REC_FOLDER_DEL           40116
#define IDC_EDIT_SET_REC_INFO_FOLDER            40117
#define IDC_BUTTON_SET_REC_INFO_FOLDER          40118
#define IDC_LIST_SET_BON                        40119
#define IDC_BUTTON_SET_BON_UP                   40120
#define IDC_BUTTON_SET_BON_DN                   40121
#define IDC_COMBO_SET_BON_COUNT                 40122
#define IDC_COMBO_SET_BON_EPG_COUNT             40123
#define IDC_STATIC_VERSION_TEXT                 40124
#define IDC_LIST_SET_EPG_SERVICE                40200
#define IDC_BUTTON_SET_EPG_SERVICE_ALL          40201
#define IDC_BUTTON_SET_EPG_SERVICE_VIDEO        40202
#define IDC_BUTTON_SET_EPG_SERVICE_CLEAR        40203
#define IDC_STATIC_SET_EPG_SERVICE              40204
#define IDC_CHECK_SET_EPG_BS                    40205
#define IDC_CHECK_SET_EPG_CS1                   40206
#define IDC_CHECK_SET_EPG_CS2                   40207
#define IDC_CHECK_SET_EPG_CS3                   40208
#define IDC_LIST_SET_EPG_TIME                   40209
#define IDC_COMBO_SET_EPG_WDAY                  40210
#define IDC_COMBO_SET_EPG_HH                    40211
#define IDC_COMBO_SET_EPG_MM                    40212
#define IDC_BUTTON_SET_EPG_TIME_ADD             40213
#define IDC_BUTTON_SET_EPG_TIME_DEL             40214
#define IDC_EDIT_SET_EPG_NG_CAP                 40215
#define IDC_EDIT_SET_EPG_NG_CAP_TUNER           40216
#define IDC_RADIO_SET_REC_END_NONE              40300
#define IDC_RADIO_SET_REC_END_STANDBY           40301
#define IDC_RADIO_SET_REC_END_SUSPEND           40302
#define IDC_RADIO_SET_REC_END_SHUTDOWN          40303
#define IDC_CHECK_SET_REBOOT                    40304
#define IDC_EDIT_SET_WAKE_TIME                  40305
#define IDC_LIST_SET_NO_EXE                     40306
#define IDC_EDIT_SET_NO_EXE                     40307
#define IDC_BUTTON_SET_NO_EXE_ADD               40308
#define IDC_BUTTON_SET_NO_EXE_DEL               40309
#define IDC_EDIT_SET_NO_STANDBY                 40310
#define IDC_CHECK_SET_NO_USE_PC                 40311
#define IDC_EDIT_SET_NO_USE_PC                  40312
#define IDC_CHECK_SET_NO_FILE_STREAMING         40313
#define IDC_CHECK_SET_NO_SHARE_FILE             40314
#define IDC_EDIT_SET_START_MARGIN               40315
#define IDC_EDIT_SET_END_MARGIN                 40316
#define IDC_EDIT_SET_APP_WAKE_TIME              40317
#define IDC_COMBO_SET_PROCESS_PRIORITY          40318
#define IDC_CHECK_SET_REC_MIN_WAKE              40319
#define IDC_CHECK_SET_OPEN_VIEW_FOR_VIEWING     40320
#define IDC_CHECK_SET_OPEN_VIEW_FOR_REC         40321
#define IDC_CHECK_SET_OPEN_VIEW_ALWAYS          40322
#define IDC_CHECK_SET_DROP_LOG                  40323
#define IDC_CHECK_SET_PG_INFO_LOG               40324
#define IDC_CHECK_SET_PG_INFO_LOG_AS_UTF8       40325
#define IDC_CHECK_SET_REC_NW                    40326
#define IDC_CHECK_SET_KEEP_DISK                 40327
#define IDC_CHECK_SET_REC_OVERWRITE             40328
#define IDC_CHECK_SET_CAPTION                   40329
#define IDC_CHECK_SET_DATA                      40330
#define IDC_CHECK_SET_BACK_PRIORITY             40400
#define IDC_CHECK_SET_FIXED_TUNER_PRIORITY      40401
#define IDC_CHECK_SET_RETRY_OTHER_TUNERS        40402
#define IDC_CHECK_SET_SEPARATE_FIXED_TUNERS     40403
#define IDC_CHECK_SET_COMMENT_AUTO_ADD          40404
#define IDC_CHECK_SET_REC_INFO_DEL_FILE         40405
#define IDC_CHECK_SET_APPLY_EXT_TO              40406
#define IDC_CHECK_SET_AUTODEL                   40407
#define IDC_LIST_SET_DEL_EXT                    40408
#define IDC_EDIT_SET_DEL_EXT                    40409
#define IDC_BUTTON_SET_DEL_EXT_ADD              40410
#define IDC_BUTTON_SET_DEL_EXT_DEL              40411
#define IDC_LIST_SET_DEL_CHK                    40412
#define IDC_EDIT_SET_DEL_CHK                    40413
#define IDC_BUTTON_SET_DEL_CHK                  40414
#define IDC_BUTTON_SET_DEL_CHK_ADD              40415
#define IDC_BUTTON_SET_DEL_CHK_DEL              40416
#define IDC_CHECK_SET_RECNAME_PLUGIN            40417
#define IDC_COMBO_SET_RECNAME_PLUGIN            40418
#define IDC_BUTTON_SET_RECNAME_PLUGIN           40419
#define IDC_CHECK_SET_NO_CHK_YEN                40420
#define IDC_RADIO_SET_DEL_RESERVE_DEL           40421
#define IDC_RADIO_SET_DEL_RESERVE_END           40422
#define IDC_RADIO_SET_DEL_RESERVE_CANCEL        40423
#define IDC_CHECK_SET_REC_INFO_FOLDER_ONLY      40424
#define IDC_CHECK_SET_FIX_NO_REC                40425
#define IDC_CHECK_SET_TCP_SERVER                40500
#define IDC_CHECK_SET_TCP_IPV6                  40501
#define IDC_EDIT_SET_TCP_PORT                   40502
#define IDC_EDIT_SET_TCP_ACL                    40503
#define IDC_EDIT_SET_TCP_RES_TO                 40504
#define IDC_CHECK_SET_AUTODEL_REC_INFO          40505
#define IDC_EDIT_SET_AUTODEL_REC_INFO           40506
#define IDC_COMBO_SET_EPG_ARCHIVE_PERIOD        40507
#define IDC_CHECK_SET_TIME_SYNC                 40508
#define IDC_CHECK_SET_RESIDENT                  40509
#define IDC_CHECK_SET_SHOW_TRAY                 40510
#define IDC_CHECK_SET_NOTIFY_TIP_STYLE          40511
#define IDC_CHECK_SET_BLINK_PRE_REC             40512
#define IDC_CHECK_SET_NO_BALLOON_TIP            40513
#define IDC_BUTTON_SET_STARTUP_ADD              40514
#define IDC_BUTTON_SET_STARTUP_DEL              40515
#define IDC_CHECK_SET_SAVE_NOTIFY_LOG           40516
#define IDC_CHECK_SET_SAVE_DEBUG_LOG            40517
#define IDC_CHECK_SET_COMPAT_TKNTREC            40518
#define IDC_EDIT_SET_TS_EXT                     40519
#define IDC_LIST_SET_VIEW_BON                   40520
#define IDC_COMBO_SET_VIEW_BON                  40521
#define IDC_BUTTON_SET_VIEW_BON_UP              40522
#define IDC_BUTTON_SET_VIEW_BON_DN              40523
#define IDC_BUTTON_SET_VIEW_BON_ADD             40524
#define IDC_BUTTON_SET_VIEW_BON_DEL             40525
#define IDC_CHECK_SET_BALLOON_TIP_REALTIME      40526
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
