<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64;x86</Platforms>
    <AssemblyVersion>0.10.70.0</AssemblyVersion>
    <FileVersion>0.10.70.0</FileVersion>
    <Copyright>Forked from: りょうちん Copyright (C) 2011-2012</Copyright>
    <ApplicationIcon>Resources\TaskIconBlue.ico</ApplicationIcon>
    <Version>0.10.70.0</Version>
    <ApplicationManifest>AppPM.manifest</ApplicationManifest>
    <RootNamespace>EpgTimer</RootNamespace>
    <AssemblyName>EpgTimer</AssemblyName>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <OutputPath>..\..\x86\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <OutputPath>..\..\x86\Release\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\..\x64\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <OutputPath>..\..\x64\Release\</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);PER_MONITOR_DPI</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\key.ico" />
    <None Remove="Resources\key_no.ico" />
    <None Remove="Resources\TaskIconBlue.ico" />
    <None Remove="Resources\TaskIconGray.ico" />
    <None Remove="Resources\TaskIconGreen.ico" />
    <None Remove="Resources\TaskIconRed.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\key.ico" />
    <Resource Include="Resources\key_no.ico" />
    <Resource Include="Resources\TaskIconBlue.ico" />
    <Resource Include="Resources\TaskIconGray.ico" />
    <Resource Include="Resources\TaskIconGreen.ico" />
    <Resource Include="Resources\TaskIconRed.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
