//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EpgDataCap_Bon.rc
//
#define IDD_EPGDATACAP_BON_DIALOG       102
#define IDD_EPGDATACAP_BON_DIALOG_1     103
#define IDD_EPGDATACAP_BON_DIALOG_2     104
#define IDI_ICON_BLUE                   129
#define IDD_DIALOG_SETTING              129
#define IDI_ICON_GRAY                   130
#define IDD_DIALOG_SET_BASIC            130
#define IDI_ICON_GREEN                  131
#define IDD_DIALOG_SET_NW               131
#define IDI_ICON_RED                    132
#define IDD_DIALOG_SET_APP              132
#define IDI_ICON_OVERLAY_EPG            133
#define IDD_DIALOG_SET_EPG              133
#define IDI_ICON_OVERLAY_REC            134
#define IDD_DIALOG_SET_APPBTN           134
#define IDD_DIALOG_SET_SERVICE          135
#define IDC_COMBO_TUNER                 1000
#define IDC_COMBO_SERVICE               1001
#define IDC_BUTTON_SET                  1002
#define IDC_BUTTON_CHSCAN               1003
#define IDC_LIST_IP_UDP                 1003
#define IDC_LIST_REC_FOLDER             1003
#define IDC_BUTTON_EPG                  1004
#define IDC_LIST_IP_TCP                 1004
#define IDC_BUTTON_REC                  1005
#define IDC_COMBO_REC_H                 1007
#define IDC_COMBO_REC_M                 1008
#define IDC_CHECK_REC_SET               1009
#define IDC_BUTTON_CANCEL               1010
#define IDC_TAB                         1010
#define IDC_CHECK_TCP                   1011
#define IDC_EDIT_SET_PATH               1011
#define IDC_CHECK_UDP                   1012
#define IDC_BUTTON_SET_PATH             1012
#define IDC_BUTTON_VIEW                 1013
#define IDC_EDIT_REC_FOLDER             1013
#define IDC_EDIT_STATUS                 1014
#define IDC_BUTTON_REC_ADD              1014
#define IDC_EDIT_LOG                    1015
#define IDC_BUTTON_REC_DEL              1015
#define IDC_EDIT_PG_INFO                1016
#define IDC_BUTTON_REC_UP               1016
#define IDC_IPADDRESS_UDP               1017
#define IDC_BUTTON_REC_DOWN             1017
#define IDC_LIST_SERVICE                1017
#define IDC_BUTTON_ADD_UDP              1018
#define IDC_BUTTON_REC_PATH             1018
#define IDC_BUTTON_ALL_CHK              1018
#define IDC_BUTTON_DEL_UDP              1019
#define IDC_CHECK_MODIFY_TITLE_BAR      1019
#define IDC_BUTTON_VIDEO_CHK            1019
#define IDC_EDIT_WAIT_SEC               1020
#define IDC_CHECK_OVERLAY_TASK_ICON     1020
#define IDC_BUTTON_ALL_CLEAR            1020
#define IDC_EDIT_PORT_UDP               1021
#define IDC_CHECK_TASKMIN               1021
#define IDC_CHECK_BS                    1021
#define IDC_CHECK_BROADCAST             1022
#define IDC_COMBO_DIALOG_TEMPLATE       1022
#define IDC_CHECK_CS1                   1022
#define IDC_EDIT_WAIT_PACKET            1023
#define IDC_CHECK_CS2                   1023
#define IDC_IPADDRESS_TCP               1024
#define IDC_CHECK_NEXTPG                1024
#define IDC_CHECK_BACK_BS               1024
#define IDC_BUTTON_ADD_TCP              1025
#define IDC_CHECK_NEED_CAPTION          1025
#define IDC_EDIT_VIEW_EXE               1025
#define IDC_CHECK_BACK_CS1              1025
#define IDC_BUTTON_DEL_TCP              1026
#define IDC_CHECK_NEED_DATA             1026
#define IDC_BUTTON_VIEW_EXE             1026
#define IDC_CHECK_BACK_CS2              1026
#define IDC_EDIT_TS_BUFF_MAX            1027
#define IDC_EDIT_VIEW_OPT               1027
#define IDC_CHECK_CS3                   1027
#define IDC_EDIT_PORT_TCP               1028
#define IDC_EDIT_WRITE_BUFF_MAX         1028
#define IDC_CHECK_BACK_CS3              1028
#define IDC_CHECK_ENABLE_DECODE         1029
#define IDC_RADIO_TCP                   1029
#define IDC_CHECK_OVER_WRITE            1030
#define IDC_RADIO_SRV_PIPE              1030
#define IDC_CHECK_ALL_SERVICE           1031
#define IDC_RADIO_PIPE                  1031
#define IDC_CHECK_EPGCAP_LIVE           1032
#define IDC_CHECK_EPGCAP_REC            1033
#define IDC_CHECK_EMM                   1035
#define IDC_COMBO_BON                   1036
#define IDC_CHECK_OPENLAST              1036
#define IDC_CHECK_SAVE_DEBUG_LOG        1037
#define IDC_BUTTON_CHK_ALL              1038
#define IDC_EDIT_REC_FILENAME           1038
#define IDC_BUTTON_CHK_VIDEO            1039
#define IDC_CHECK_NO_LOG_SCRAMBLE       1039
#define IDC_CHECK_PARSE_EPG_POST_PROC   1040
#define IDC_BUTTON_CHK_CLEAR            1040
#define IDC_EDIT_DROP_SAVE_THRESH       1041
#define IDC_EDIT_CH                     1041
#define IDC_EDIT_SCRAMBLE_SAVE_THRESH   1042
#define IDC_BUTTON_DEL                  1042
#define IDC_CHECK_DROP_LOG_AS_UTF8      1043
#define IDC_EDIT_BACKSTART_WAITSEC      1044
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
